[project]
name = "aoc2024"
version = "0.1.0"
description = "Advent of Code 2024 solutions in Python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.3.4",
    "requests>=2.32.3",
]
